### ISSUE TITLE
Program tested failed on Windows

### ISSUE THREAD

**Issue by xuhao1** [charlylima/XPlaneUDP#1]
C:\ProgramData\Anaconda3\python.exe "C:\Program Files\JetBrains\PyCharm 2017.2\helpers\pycharm\_jb_nosetest_runner.py" --path C:/Users/xuhao/Desktop/FlightDevelop/XPlaneUDP/XPlaneUdp_Unittest.py
Testing started at 16:57 ...
Launching Nosetest with arguments C:\Program Files\JetBrains\PyCharm 2017.2\helpers\pycharm\_jb_nosetest_runner.py C:/Users/xuhao/Desktop/FlightDevelop/XPlaneUDP/XPlaneUdp_Unittest.py in C:\Users\xuhao\Desktop\FlightDevelop\XPlaneUDP
E

ERROR: test1 (XPlaneUdp_Unittest.TestXplaneUdp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\xuhao\Desktop\FlightDevelop\XPlaneUDP\XPlaneUdp_Unittest.py", line 14, in test1
    beacon = xp.FindIp()
  File "C:\Users\xuhao\Desktop\FlightDevelop\XPlaneUDP\XPlaneUdp.py", line 113, in FindIp
    sock.bind((self.MCAST_GRP, self.MCAST_PORT))
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\ProgramData\Anaconda3\lib\unittest\case.py", line 601, in run
    testMethod()
  File "C:\Users\xuhao\Desktop\FlightDevelop\XPlaneUDP\XPlaneUdp_Unittest.py", line 14, in test1
    beacon = xp.FindIp()
  File "C:\Users\xuhao\Desktop\FlightDevelop\XPlaneUDP\XPlaneUdp.py", line 113, in FindIp
    sock.bind((self.MCAST_GRP, self.MCAST_PORT))
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

Process finished with exit code 1

**Comment by xuhao1** [comment]
Test on X-Plane 11 steam with Windows 10 64-bit, python 3.6.1(64-bit) Anaconda 4.4.0 (64-bit)

**Comment by xuhao1** [comment]
Problem will fix when change XPlaneUDP.py line 113 from
` sock.bind((self.MCAST_GRP, self.MCAST_PORT))`
to
`sock.bind(('', self.MCAST_PORT))`

Guess this problem is cause by windows system

**Comment by praveenethiraj** [comment]
Hello, I did not have this issue earlier but since I performed a Windows update this error has appeared and even when I perform the change on line 113 it does not resolve the issue. 

Could you let me know if there's anything else I am missing please?

![image](https://user-images.githubusercontent.com/77687233/113718980-7805e580-96ed-11eb-8ee5-afc6a8786b9d.png)
