### ISSUE TITLE
Win 10 and Xplane 11.50+

### ISSUE THREAD

**Issue by albafer** [charlylima/XPlaneUDP#5]
Hi, 

I'm cheking the script XPlane10UdpRequestDataRefs.py but for any reason after "data, addr = sock.recvfrom(1024)" the program freeze...

I'm not a expert with python but could you help me?

Best regards and thank you in advance!

**Comment by charlylima** [comment]
This might be fixed by commit 1beb0434f326a705f7193a2a8bab2128e1c0a672, but I have not tested on windows.
