### ISSUE TITLE
Only receiving one DataRef

### ISSUE THREAD

**Issue by davesimpson99** [charlylima/XPlaneUDP#9]
Hi,
Trying the code with X-Plane 11.55 on Windows 11.
Only one dataref (the first in the list) is returned, I added debug to print numvalues and it always shows 1 even though I have added 3.
This happens with both XPlaneUDP.py and XPRequestDRefs.py 
The XPlaneUDPunittest.py then fails when run. Screenshots attached.

Obviously this code has been running great previously. Has XPlane changed the way it returns DRefs? Any ideas welcome, thanks!

<img width="694" alt="Screenshot XplaneUDPpy" src="https://user-images.githubusercontent.com/39417748/220184928-f02f2685-0ee0-433e-96d2-23d465d26f22.png">
<img width="620" alt="Screenshot XPRequestDRefspy" src="https://user-images.githubusercontent.com/39417748/220185027-84a4da6a-fd6c-48c1-b3bb-ef00226d8f65.png">
<img width="871" alt="Screenshot XplaneUDPunittest" src="https://user-images.githubusercontent.com/39417748/220184958-fd192c71-ab11-47b1-a0d1-ad57b1af4afd.png">

**Comment by davesimpson99** [comment]
Tested on raspberry pi Buster and it works fine. Its a Windows issue. It also works fine if I run the code on windows under the VS Code debugger, but not if its run without debugging! ?????

**Comment by bendanville** [comment]
> Hi, Trying the code with X-Plane 11.55 on Windows 11. Only one dataref (the first in the list) is returned, I added debug to print numvalues and it always shows 1 even though I have added 3. This happens with both XPlaneUDP.py and XPRequestDRefs.py The XPlaneUDPunittest.py then fails when run. Screenshots attached.

How many updates do you need per second?
I've had success with XplaneConnect's python implementation on windows: https://github.com/nasa/XPlaneConnect
The C# implementation for me fails after a few minutes and I am not enough of a C programmer to work out why
